<div
  class="xl:p-4 p-4 h-full xl:h-[calc(100%-48px)] w-full bg-veryPaleRed flex flex-col"
>
  <div class="xl:p-4 p-2 text-2xl xl:text-4xl  z-10 page-title font-semibold">
    Music
  </div>
  <div
    class="w-full p-4 m-auto space-y-8 max-h-full xl:max-h-full overflow-y-scroll"
  >
    <iframe
      class="m-auto"
      title="soundcloud"
      width="69%"
      height="166"
      scrolling="no"
      frameborder="no"
      allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1353805186&color=%23f25f3a&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
    />

    <iframe
      class="m-auto"
      title="soundcloud"
      width="69%"
      height="166"
      scrolling="no"
      frameborder="no"
      allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1350634141&color=%23f25f3a&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
    />

    <iframe
      class="m-auto"
      title="soundcloud"
      width="69%"
      height="166"
      scrolling="no"
      frameborder="no"
      allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1301435839&color=%23f25f3a&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
    />
    <iframe
      class="m-auto"
      title="soundcloud"
      width="69%"
      height="166"
      scrolling="no"
      frameborder="no"
      allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1278612760&color=%23f25f3a&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
    />
    <iframe
      class="m-auto"
      title="soundcloud"
      width="69%"
      height="166"
      scrolling="no"
      frameborder="no"
      allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1259061217&color=%23f25f3a&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
    />
    <iframe
      class="m-auto"
      title="soundcloud"
      width="69%"
      height="166"
      scrolling="no"
      frameborder="no"
      allow="autoplay"
      src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/1244042866&color=%23f25f3a&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"
    />
  </div>
</div>
